apiVersion: v1
kind: Secret
metadata:
  name: aws-fluentd-credential
  namespace: default
data:
  aws_region: dXMtZWFzdC0x
  aws_access_key_id: QUtJQTRVUjNON1BFRkhMRk1GNFA=
  aws_secret_access_key: ZTJjU2VEUHVMTzVocm54SDVydWZhOEJjNS9acm10c3hYMmZaVkZLYw==