language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin


install:
  - docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel
  - docker push jsleung1/reverseproxy:${TRAVIS_BUILD_ID}
  - docker push jsleung1/udacity-restapi-user:${TRAVIS_BUILD_ID}
  - docker push jsleung1/udacity-restapi-feed:${TRAVIS_BUILD_ID}
  - docker push jsleung1/udacity-frontend:${TRAVIS_BUILD_ID}
  - docker tag jsleung1/reverseproxy:${TRAVIS_BUILD_ID} jsleung1/reverseproxy:latest
  - docker tag jsleung1/udacity-restapi-user:${TRAVIS_BUILD_ID} jsleung1/udacity-restapi-user:latest
  - docker tag jsleung1/udacity-restapi-feed:${TRAVIS_BUILD_ID} jsleung1/udacity-restapi-feed:latest
  - docker tag jsleung1/udacity-frontend:${TRAVIS_BUILD_ID} jsleung1/udacity-frontend:latest
  - docker push jsleung1/reverseproxy:latest
  - docker push jsleung1/udacity-restapi-user:latest
  - docker push jsleung1/udacity-restapi-feed:latest
  - docker push jsleung1/udacity-frontend:latest
  - sed -i -e 's|KUBE_CA_CERT|'"${KUBE_CA_CERT}"'|g' terraform/aws/udacitykubeone-kubeconfig-bare-travis
  - sed -i -e 's|KUBE_ENDPOINT|'"${KUBE_ENDPOINT}"'|g' terraform/aws/udacitykubeone-kubeconfig-bare-travis
  - sed -i -e 's|KUBE_ADMIN_CERT|'"${KUBE_ADMIN_CERT}"'|g' terraform/aws/udacitykubeone-kubeconfig-bare-travis
  - sed -i -e 's|KUBE_ADMIN_KEY|'"${KUBE_ADMIN_KEY}"'|g' terraform/aws/udacitykubeone-kubeconfig-bare-travis
  - kubectl --kubeconfig terraform/aws/udacitykubeone-kubeconfig-bare-travis set image deployment/reverseproxy reverseproxy=jsleung1/reverseproxy:$TRAVIS_BUILD_ID
  - kubectl --kubeconfig terraform/aws/udacitykubeone-kubeconfig-bare-travis set image deployment/backend-feed backend-feed=jsleung1/udacity-restapi-feed:$TRAVIS_BUILD_ID
  - kubectl --kubeconfig terraform/aws/udacitykubeone-kubeconfig-bare-travis set image deployment/backend-user backend-user=jsleung1/udacity-restapi-user:$TRAVIS_BUILD_ID
  - kubectl --kubeconfig terraform/aws/udacitykubeone-kubeconfig-bare-travis set image deployment/frontend frontend=jsleung1/udacity-frontend:$TRAVIS_BUILD_ID